package com.lyyexample.mapper;

import com.lyyexample.entry.LyyTest;

public interface LyyTestMapper {
    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table lyy_test
     *
     * @mbggenerated
     */
    int deleteByPrimaryKey(Integer id);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table lyy_test
     *
     * @mbggenerated
     */
    int insert(LyyTest record);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table lyy_test
     *
     * @mbggenerated
     */
    int insertSelective(LyyTest record);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table lyy_test
     *
     * @mbggenerated
     */
    LyyTest selectByPrimaryKey(Integer id);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table lyy_test
     *
     * @mbggenerated
     */
    int updateByPrimaryKeySelective(LyyTest record);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table lyy_test
     *
     * @mbggenerated
     */
    int updateByPrimaryKey(LyyTest record);
}